### ISSUE TITLE
How to convert final Haiku model to ONNX model?

### ISSUE THREAD

**Issue by changkaiyan** [deepmind/tracr#3]

**Comment by mrahtz** [comment]
I'm actually not super familiar with ONNX, so I'm not sure I can offer any good advice beyond what I presume is available in existing documentation, eg https://colab.sandbox.google.com/gist/tomhennigan/5e3d316ec6ebd81500a660155770e34a/example-of-jax-haiku-onnx.ipynb.

I'll close this for now, since I think it's slightly outside the scope of what we're willing to provide support for, but please do leave a followup comment if you get it working - we'll document it in the README in case anyone else wants to do this.
